// User types
export const SET_AUTHENTICATION = "SET_AUTHENTICATION";
export const SET_UNAUTHENTICATION = "SET_UNAUTHENTICATION";
export const SET_USER = "SET_USER";
export const SET_PROFILE = "SET_PROFILE";
export const LOADING_USER = "LOADING_USER";
export const MARK_NOTIFICATION_READED = "MARK_NOTIFICATION_READED";
export const SET_ERROR_USER = "SET_ERROR_USER";
export const SET_LIKE_USER = "SET_LIKE_USER";
export const SET_UNLIKE_USER = "SET_UNLIKE_USER";

// Postingan types
export const SET_ALL_POSTINGAN = "SET_ALL_POSTINGAN";
export const SET_SINGLE_POSTINGAN = "SET_SINGLE_POSTINGAN";
export const SET_USER_POSTINGAN = "SET_USER_POSTINGAN";
export const LOADING_POSTINGAN = "LOADING_POSTINGAN";
export const RESET_SINGLE_POST = "RESET_SINGLE_POST";
export const POST_POSTINGAN = "POST_POSTINGAN";
export const SET_ERROR_POSTINGAN = "SET_ERROR_POSTINGAN";
export const SUBMIT_COMMENT = "SUBMIT_COMMENT";
export const LIKE_POSTINGAN = "LIKE_POSTINGAN";
export const UNLIKE_POSTINGAN = "UNLIKE_POSTINGAN";
export const DELETE_POSTINGAN = "DELETE_POSTINGAN";

// Data types
export const SET_FLASH = "SET_FLASH";
export const CLOSE_FLASH = "CLOSE_FLASH";
export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const LOADING_DATA = "LOADING_DATA";
